export interface Product {
    id: string
    name: string
    description: string
    price: number
    originalPrice: number | null
    images: string[]
    category: string
    materials: string[]
    gemstones: string[]
    rating: number
    reviewCount: number
    inStock: boolean
    isNew: boolean
    featured: boolean
    soldCount: number
    createdAt: string
}

export const products: Product[] = [
    {
        id: "1",
        name: "Diamond Solitaire Engagement Ring",
        description: "A timeless 1.5 carat diamond solitaire set in 18k white gold. The perfect symbol of eternal love.",
        price: 4999,
        originalPrice: 5499,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "rings",
        materials: ["White Gold", "18k Gold"],
        gemstones: ["Diamond"],
        rating: 4.9,
        reviewCount: 128,
        inStock: true,
        isNew: false,
        featured: true,
        soldCount: 89,
        createdAt: "2024-12-01T00:00:00Z",
    },
    {
        id: "2",
        name: "Sapphire and Diamond Halo Necklace",
        description:
            "A stunning blue sapphire surrounded by a halo of brilliant diamonds, suspended on an 18k white gold chain.",
        price: 2799,
        originalPrice: 3299,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "necklaces",
        materials: ["White Gold", "18k Gold"],
        gemstones: ["Sapphire", "Diamond"],
        rating: 4.8,
        reviewCount: 76,
        inStock: true,
        isNew: false,
        featured: true,
        soldCount: 62,
        createdAt: "2024-11-15T00:00:00Z",
    },
    {
        id: "3",
        name: "Pearl Drop Earrings",
        description:
            "Elegant South Sea pearl earrings with diamond accents set in 14k yellow gold. Perfect for special occasions.",
        price: 1299,
        originalPrice: null,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "earrings",
        materials: ["Yellow Gold", "14k Gold"],
        gemstones: ["Pearl", "Diamond"],
        rating: 4.7,
        reviewCount: 54,
        inStock: true,
        isNew: true,
        featured: false,
        soldCount: 41,
        createdAt: "2025-04-10T00:00:00Z",
    },
    {
        id: "4",
        name: "Emerald Tennis Bracelet",
        description:
            "A luxurious tennis bracelet featuring 25 emerald-cut emeralds set in platinum. A true statement piece.",
        price: 7999,
        originalPrice: 8999,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "bracelets",
        materials: ["Platinum"],
        gemstones: ["Emerald"],
        rating: 5.0,
        reviewCount: 32,
        inStock: true,
        isNew: false,
        featured: true,
        soldCount: 18,
        createdAt: "2024-10-05T00:00:00Z",
    },
    {
        id: "5",
        name: "Vintage-Inspired Ruby Ring",
        description:
            "A vintage-inspired design featuring a 1.2 carat oval ruby surrounded by a halo of diamonds in rose gold.",
        price: 2499,
        originalPrice: null,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "rings",
        materials: ["Rose Gold", "14k Gold"],
        gemstones: ["Ruby", "Diamond"],
        rating: 4.6,
        reviewCount: 47,
        inStock: true,
        isNew: false,
        featured: false,
        soldCount: 35,
        createdAt: "2024-09-20T00:00:00Z",
    },
    {
        id: "6",
        name: "Men's Luxury Chronograph Watch",
        description:
            "A sophisticated men's chronograph watch with a stainless steel case, sapphire crystal, and genuine leather strap.",
        price: 3499,
        originalPrice: 3999,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "watches",
        materials: ["Stainless Steel", "Leather"],
        gemstones: [],
        rating: 4.8,
        reviewCount: 89,
        inStock: true,
        isNew: false,
        featured: true,
        soldCount: 72,
        createdAt: "2024-08-15T00:00:00Z",
    },
    {
        id: "7",
        name: "Diamond Stud Earrings",
        description: "Classic 1 carat total weight diamond stud earrings set in 14k white gold with secure screw backs.",
        price: 1999,
        originalPrice: null,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "earrings",
        materials: ["White Gold", "14k Gold"],
        gemstones: ["Diamond"],
        rating: 4.9,
        reviewCount: 215,
        inStock: true,
        isNew: false,
        featured: true,
        soldCount: 187,
        createdAt: "2024-07-10T00:00:00Z",
    },
    {
        id: "8",
        name: "Amethyst and Diamond Pendant",
        description:
            "A stunning pear-shaped amethyst pendant accented with diamonds, suspended on an 18k white gold chain.",
        price: 1299,
        originalPrice: 1599,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "necklaces",
        materials: ["White Gold", "18k Gold"],
        gemstones: ["Amethyst", "Diamond"],
        rating: 4.7,
        reviewCount: 63,
        inStock: true,
        isNew: true,
        featured: false,
        soldCount: 48,
        createdAt: "2025-04-05T00:00:00Z",
    },
    {
        id: "9",
        name: "Gold Chain Bracelet",
        description: "A sophisticated 14k yellow gold chain bracelet with a modern design. Perfect for everyday wear.",
        price: 899,
        originalPrice: null,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "bracelets",
        materials: ["Yellow Gold", "14k Gold"],
        gemstones: [],
        rating: 4.5,
        reviewCount: 87,
        inStock: true,
        isNew: false,
        featured: false,
        soldCount: 76,
        createdAt: "2024-06-20T00:00:00Z",
    },
    {
        id: "10",
        name: "Three-Stone Diamond Engagement Ring",
        description: "A meaningful three-stone diamond ring representing your past, present, and future together.",
        price: 3999,
        originalPrice: null,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "rings",
        materials: ["Platinum"],
        gemstones: ["Diamond"],
        rating: 4.9,
        reviewCount: 104,
        inStock: true,
        isNew: false,
        featured: true,
        soldCount: 82,
        createdAt: "2024-05-15T00:00:00Z",
    },
    {
        id: "11",
        name: "Women's Diamond Watch",
        description:
            "An elegant women's watch with a mother-of-pearl dial, diamond hour markers, and a stainless steel bracelet.",
        price: 2799,
        originalPrice: 3299,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "watches",
        materials: ["Stainless Steel", "Mother of Pearl"],
        gemstones: ["Diamond"],
        rating: 4.7,
        reviewCount: 68,
        inStock: true,
        isNew: true,
        featured: false,
        soldCount: 53,
        createdAt: "2025-03-10T00:00:00Z",
    },
    {
        id: "12",
        name: "Sapphire and Diamond Hoop Earrings",
        description: "Luxurious hoop earrings featuring alternating blue sapphires and diamonds set in 18k white gold.",
        price: 1899,
        originalPrice: 2299,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "earrings",
        materials: ["White Gold", "18k Gold"],
        gemstones: ["Sapphire", "Diamond"],
        rating: 4.8,
        reviewCount: 42,
        inStock: true,
        isNew: false,
        featured: false,
        soldCount: 31,
        createdAt: "2024-04-25T00:00:00Z",
    },
    {
        id: "13",
        name: "Pearl Strand Necklace",
        description:
            "A classic strand of graduated Akoya pearls with a 14k white gold clasp. Timeless elegance for any occasion.",
        price: 1499,
        originalPrice: null,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "necklaces",
        materials: ["White Gold", "14k Gold"],
        gemstones: ["Pearl"],
        rating: 4.9,
        reviewCount: 97,
        inStock: true,
        isNew: false,
        featured: true,
        soldCount: 85,
        createdAt: "2024-03-15T00:00:00Z",
    },
    {
        id: "14",
        name: "Diamond Bangle Bracelet",
        description:
            "A stunning diamond bangle bracelet featuring 2 carats of round brilliant diamonds set in 18k yellow gold.",
        price: 4299,
        originalPrice: 4999,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "bracelets",
        materials: ["Yellow Gold", "18k Gold"],
        gemstones: ["Diamond"],
        rating: 4.8,
        reviewCount: 56,
        inStock: true,
        isNew: false,
        featured: false,
        soldCount: 42,
        createdAt: "2024-02-20T00:00:00Z",
    },
    {
        id: "15",
        name: "Emerald Cut Diamond Ring",
        description: "A sophisticated emerald-cut diamond ring with tapered baguette side stones set in platinum.",
        price: 5999,
        originalPrice: null,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "rings",
        materials: ["Platinum"],
        gemstones: ["Diamond"],
        rating: 5.0,
        reviewCount: 38,
        inStock: true,
        isNew: true,
        featured: true,
        soldCount: 24,
        createdAt: "2025-02-05T00:00:00Z",
    },
    {
        id: "16",
        name: "Men's Signet Ring",
        description:
            "A classic men's signet ring crafted in solid 14k yellow gold. Can be personalized with custom engraving.",
        price: 899,
        originalPrice: 1099,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "rings",
        materials: ["Yellow Gold", "14k Gold"],
        gemstones: [],
        rating: 4.6,
        reviewCount: 72,
        inStock: true,
        isNew: false,
        featured: false,
        soldCount: 63,
        createdAt: "2024-01-15T00:00:00Z",
    },
    {
        id: "17",
        name: "Ruby and Diamond Drop Earrings",
        description: "Elegant drop earrings featuring pear-shaped rubies surrounded by diamonds, set in 18k white gold.",
        price: 2499,
        originalPrice: 2999,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "earrings",
        materials: ["White Gold", "18k Gold"],
        gemstones: ["Ruby", "Diamond"],
        rating: 4.7,
        reviewCount: 45,
        inStock: true,
        isNew: false,
        featured: false,
        soldCount: 36,
        createdAt: "2023-12-10T00:00:00Z",
    },
    {
        id: "18",
        name: "Luxury Dive Watch",
        description: "A professional dive watch with 300m water resistance, ceramic bezel, and automatic movement.",
        price: 4299,
        originalPrice: null,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "watches",
        materials: ["Stainless Steel", "Ceramic"],
        gemstones: [],
        rating: 4.9,
        reviewCount: 83,
        inStock: true,
        isNew: false,
        featured: true,
        soldCount: 71,
        createdAt: "2023-11-20T00:00:00Z",
    },
    {
        id: "19",
        name: "Diamond Cross Pendant",
        description:
            "A meaningful diamond cross pendant featuring 0.5 carats of round brilliant diamonds set in 14k white gold.",
        price: 1299,
        originalPrice: 1599,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "necklaces",
        materials: ["White Gold", "14k Gold"],
        gemstones: ["Diamond"],
        rating: 4.8,
        reviewCount: 67,
        inStock: true,
        isNew: false,
        featured: false,
        soldCount: 58,
        createdAt: "2023-10-15T00:00:00Z",
    },
    {
        id: "20",
        name: "Charm Bracelet",
        description:
            "A sterling silver charm bracelet with five pre-attached charms. Add your own charms to create a personal story.",
        price: 299,
        originalPrice: 399,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "bracelets",
        materials: ["Silver"],
        gemstones: [],
        rating: 4.5,
        reviewCount: 124,
        inStock: true,
        isNew: true,
        featured: false,
        soldCount: 112,
        createdAt: "2025-01-10T00:00:00Z",
    },
    {
        id: "21",
        name: "Opal and Diamond Ring",
        description:
            "A unique ring featuring an Australian opal center stone surrounded by a halo of diamonds set in 14k rose gold.",
        price: 1899,
        originalPrice: null,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "rings",
        materials: ["Rose Gold", "14k Gold"],
        gemstones: ["Opal", "Diamond"],
        rating: 4.7,
        reviewCount: 53,
        inStock: true,
        isNew: false,
        featured: false,
        soldCount: 41,
        createdAt: "2023-09-20T00:00:00Z",
    },
    {
        id: "22",
        name: "Diamond Infinity Necklace",
        description: "A meaningful infinity symbol pendant adorned with diamonds, suspended on an 18k white gold chain.",
        price: 999,
        originalPrice: 1299,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "necklaces",
        materials: ["White Gold", "18k Gold"],
        gemstones: ["Diamond"],
        rating: 4.8,
        reviewCount: 92,
        inStock: true,
        isNew: false,
        featured: false,
        soldCount: 84,
        createdAt: "2023-08-15T00:00:00Z",
    },
    {
        id: "23",
        name: "Sapphire Stud Earrings",
        description: "Classic blue sapphire stud earrings set in 14k yellow gold with secure screw backs.",
        price: 899,
        originalPrice: null,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "earrings",
        materials: ["Yellow Gold", "14k Gold"],
        gemstones: ["Sapphire"],
        rating: 4.6,
        reviewCount: 78,
        inStock: true,
        isNew: false,
        featured: false,
        soldCount: 65,
        createdAt: "2023-07-10T00:00:00Z",
    },
    {
        id: "24",
        name: "Diamond Tennis Bracelet",
        description:
            "A classic diamond tennis bracelet featuring 3 carats of round brilliant diamonds set in 18k white gold.",
        price: 5999,
        originalPrice: 6999,
        images: [
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
            "/placeholder.svg?height=400&width=400",
        ],
        category: "bracelets",
        materials: ["White Gold", "18k Gold"],
        gemstones: ["Diamond"],
        rating: 5.0,
        reviewCount: 47,
        inStock: true,
        isNew: false,
        featured: true,
        soldCount: 32,
        createdAt: "2023-06-20T00:00:00Z",
    },
]
